<?php
use CRM_Accountsync_ExtensionUtil as E;

return [
  'name' => 'AccountInvoice',
  'table' => 'civicrm_account_invoice',
  'class' => 'CRM_Accountsync_DAO_AccountInvoice',
  'getInfo' => fn() => [
    'title' => E::ts('Account Invoice'),
    'title_plural' => E::ts('Account Invoices'),
    'description' => E::ts('Account System Invoices'),
    'log' => TRUE,
    'add' => '4.4',
  ],
  'getIndices' => fn() => [
    'index_contribution_invoice' => [
      'fields' => [
        'contribution_id' => TRUE,
      ],
      'add' => '4.4',
    ],
    'UI_account_system_id' => [
      'fields' => [
        'accounts_invoice_id' => TRUE,
        'connector_id' => TRUE,
        'plugin' => TRUE,
      ],
      'unique' => TRUE,
      'add' => '5.0',
    ],
    'UI_invoice_id_plugin' => [
      'fields' => [
        'contribution_id' => TRUE,
        'connector_id' => TRUE,
        'plugin' => TRUE,
      ],
      'unique' => TRUE,
      'add' => '5.0',
    ],
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => E::ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => NULL,
      'required' => TRUE,
      'readonly' => TRUE,
      'description' => E::ts('Unique AccountInvoice ID'),
      'add' => '4.4',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'contribution_id' => [
      'title' => E::ts('Contribution ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Text',
      'description' => E::ts('FK to contribution table.'),
      'add' => '4.4',
      'default' => NULL,
      'entity_reference' => [
        'entity' => 'Contribution',
        'key' => 'id',
        'on_delete' => 'SET NULL',
      ],
    ],
    'accounts_invoice_id' => [
      'title' => E::ts('Accounts Invoice ID'),
      'sql_type' => 'varchar(128)',
      'input_type' => 'Text',
      'description' => E::ts('External Reference'),
      'add' => '4.4',
      'default' => NULL,
    ],
    'accounts_status_id' => [
      'title' => E::ts('Accounts Status ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('Status in accounts system (mapped to civicrm definition)'),
      'add' => '4.4',
      'default' => 0,
      'input_attrs' => [
        'label' => E::ts('Accounting system status'),
      ],
      'pseudoconstant' => [
        'callback' => 'CRM_Accountsync_BAO_AccountInvoice::getAccountStatuses',
      ],
    ],
    'last_sync_date' => [
      'title' => E::ts('Last Sync Date'),
      'sql_type' => 'timestamp',
      'input_type' => 'Select Date',
      'required' => TRUE,
      'readonly' => TRUE,
      'description' => E::ts('When was the contact last synced.'),
      'add' => '4.4',
      'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
      'input_attrs' => [
        'format_type' => 'activityDateTime',
        'label' => E::ts('Last Sync Date'),
      ],
    ],
    'accounts_modified_date' => [
      'title' => E::ts('Accounts Modified Date'),
      'sql_type' => 'timestamp',
      'input_type' => 'Select Date',
      'readonly' => TRUE,
      'description' => E::ts('When was the invoice last Altered in the accounts system.'),
      'add' => '4.4',
      'input_attrs' => [
        'format_type' => 'activityDateTime',
        'label' => E::ts('Last Modified Date'),
      ],
    ],
    'accounts_data' => [
      'title' => E::ts('Account System Data'),
      'sql_type' => 'text',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('json array of data as returned from accounts system'),
      'add' => '4.4',
      'default' => NULL,
    ],
    'error_data' => [
      'title' => E::ts('Account Error Data'),
      'sql_type' => 'text',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('json array of error data as returned from accounts system'),
      'add' => '4.4',
      'default' => NULL,
    ],
    'accounts_needs_update' => [
      'title' => E::ts('Accounts Needs Update'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('Include in next push to accounts'),
      'add' => '4.4',
      'default' => FALSE,
    ],
    'connector_id' => [
      'title' => E::ts('Connector ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('ID of connector. Relevant to connect to more than one account of the same type'),
      'add' => '4.4',
      'default' => 0,
      'input_attrs' => [
        'label' => E::ts('Connection'),
      ],
    ],
    'is_error_resolved' => [
      'title' => E::ts('Error Resolved'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('Filter out if resolved'),
      'add' => '5.56',
      'default' => FALSE,
    ],
    'plugin' => [
      'title' => E::ts('Account Plugin'),
      'sql_type' => 'varchar(32)',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('Name of plugin creating the account'),
      'add' => '4.4',
    ],
  ],
];
