<?php
use CRM_Accountsync_ExtensionUtil as E;

return [
  'name' => 'AccountContact',
  'table' => 'civicrm_account_contact',
  'class' => 'CRM_Accountsync_DAO_AccountContact',
  'getInfo' => fn() => [
    'title' => E::ts('Account Contact'),
    'title_plural' => E::ts('Account Contacts'),
    'description' => E::ts('Contacts Synced to Accounts package'),
    'log' => TRUE,
    'add' => '4.4',
  ],
  'getIndices' => fn() => [
    'UI_account_system_id' => [
      'fields' => [
        'accounts_contact_id' => TRUE,
        'connector_id' => TRUE,
        'plugin' => TRUE,
      ],
      'unique' => TRUE,
      'add' => '5.0',
    ],
    'UI_contact_id_plugin' => [
      'fields' => [
        'contact_id' => TRUE,
        'connector_id' => TRUE,
        'plugin' => TRUE,
      ],
      'unique' => TRUE,
      'add' => '5.0',
    ],
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => E::ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => NULL,
      'required' => TRUE,
      'readonly' => TRUE,
      'description' => E::ts('Unique AccountContact ID'),
      'add' => '4.4',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'contact_id' => [
      'title' => E::ts('Contact ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'description' => E::ts('FK to Contact'),
      'add' => '4.4',
      'input_attrs' => [
        'label' => E::ts('CiviCRM Contact ID'),
      ],
      'entity_reference' => [
        'entity' => 'Contact',
        'key' => 'id',
        'on_delete' => 'CASCADE',
      ],
    ],
    'accounts_contact_id' => [
      'title' => E::ts('Accounts Contact ID'),
      'sql_type' => 'varchar(128)',
      'input_type' => 'Text',
      'description' => E::ts('External Reference'),
      'add' => '4.4',
    ],
    'accounts_display_name' => [
      'title' => E::ts('Display Name'),
      'sql_type' => 'varchar(128)',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('Name from Accounts Package'),
      'add' => '4.4',
    ],
    'last_sync_date' => [
      'title' => E::ts('Last Sync Date'),
      'sql_type' => 'timestamp',
      'input_type' => NULL,
      'readonly' => TRUE,
      'description' => E::ts('When was the contact last synced.'),
      'add' => '4.4',
      'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ],
    'accounts_modified_date' => [
      'title' => E::ts('Accounts Modified Date'),
      'sql_type' => 'timestamp',
      'input_type' => NULL,
      'readonly' => TRUE,
      'description' => E::ts('When was the invoice last Altered in the accounts system.'),
      'add' => '4.4',
    ],
    'accounts_data' => [
      'title' => E::ts('Account System Data'),
      'sql_type' => 'text',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('json array of data as returned from accounts system'),
      'add' => '4.4',
    ],
    'error_data' => [
      'title' => E::ts('Account Error Data'),
      'sql_type' => 'text',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('json array of error data as returned from accounts system'),
      'add' => '4.4',
    ],
    'accounts_needs_update' => [
      'title' => E::ts('Accounts Needs Update'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('Include in next push to accounts'),
      'add' => '4.4',
      'default' => TRUE,
    ],
    'connector_id' => [
      'title' => E::ts('Connector ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Text',
      'readonly' => TRUE,
      'description' => E::ts('ID of connector. Relevant to connect to more than one account of the same type'),
      'add' => '4.4',
      'default' => 0,
    ],
    'plugin' => [
      'title' => E::ts('Account Plugin'),
      'sql_type' => 'varchar(32)',
      'input_type' => NULL,
      'readonly' => TRUE,
      'description' => E::ts('Name of plugin creating the account'),
      'add' => '4.4',
    ],
    'do_not_sync' => [
      'title' => E::ts('Do Not Sync'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('Do not sync this contact'),
      'add' => '4.6',
      'default' => FALSE,
    ],
    'is_error_resolved' => [
      'title' => E::ts('Error Resolved'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'description' => E::ts('Filter out if resolved'),
      'add' => '5.56',
      'default' => FALSE,
    ],
  ],
];
